### ISSUE TITLE
fix: simple and linear git history

### ISSUE THREAD

**Issue by ARiYaNSEp0-0** [HamidMolareza/QueraLens#17]
I want to know your opinion about having more linear and simple git history. Right now we have few commits and yet I think our git history is like complex and full of extra merge commits. How about using rebase or squashing or some strategy to at least master and dev have linear and understandable history.

**Comment by ARiYaNSEp0-0** [comment]
current git history [graph](https://github.com/HamidMolareza/QueraLens/network)

**Comment by HamidMolareza** [comment]
In GitHub settings, it is possible to block merging PRs directly into the `main` branch, allowing only rebase or squash merges. This way, if a PR includes a single feature, we can use **squash**, and if there are multiple features with several distinct commits, we can use **rebase**.

For other branches that are not protected, as a general rule, you should never modify commits or history that have been pushed and might already be accessed by others. Changes should only be made to local commits or commits you are certain no one else has access to. For example:  
- In the **TDD** approach, it is quite common to use multiple commits to solve even a simple problem. In such cases, to keep the commit history clean—especially for code reviews—it is necessary to use **squash**.  
- When working on a feature and a branch like `feat/my-feat`, and you’re sure you’re the only one working on it, it’s a good practice to rebase your branch with `dev` before pushing. (Doing this before pushing our feature ensures that our changes are in sync with the latest changes in the `dev` branch, which might have been modified by others)

In this repository, to avoid issues, the ability to force push to the `main` and `dev` branches has been blocked.

**Comment by ARiYaNSEp0-0** [comment]
Thank you so much 🙏🙏. From now on, I will use rebase for local branches before pushing
